apiVersion: v1
kind: Pod
metadata:
  namespace: test
  name: ubuntu
  labels:
    app: ubuntu
spec:
  containers:
  - image: ubuntu
    name: ubuntu
    tty: true
    stdin: true
    resources:
      limits:
        cpu: "200m"
        memory: "1Gi"

